### ISSUE TITLE
can not use gorm in gf 1.6.4 

### ISSUE THREAD

**Issue by GuihaiHU** [gogf/gf#1338]
### 1. What version of `Go` and system type/arch are you using?

go version go1.15.6 darwin/amd64

### 2. What version of `GoFrame` are you using?

github.com/gogf/gf v1.16.4

### 3. Can this issue be re-produced with the latest release?

yes

### 4. What did you do?

I use gorm install of gogf-gdb. It ran well before but throw exception if I upgrade gogf to 1.6.4
```
panic: sql: Register called twice for driver mysql

goroutine 1 [running]:
database/sql.Register(0x1afdd2a, 0x5, 0x1cc4ee0, 0x23a2358)
        /usr/local/go/src/database/sql/sql.go:51 +0x187
github.com/go-sql-driver/mysql.init.0()
        /Users/ahaihu/workspaces/go/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/driver.go:84 +0x4e
```

**Comment by zcool321** [comment]
try master branch

**Comment by zfha** [comment]
> try master branch

master 也不行呢 @zcool321

**Comment by zfha** [comment]
我现在的版本是github.com/gogf/gf v1.16.5-0.20210715141900-88009ee2781f，请问大神怎么解决呢？

**Comment by zcool321** [comment]
这个问题我记得是 一个分支问题~  升级master就好了~

你可以在尝试这个分支试试：github.com/gogf/gf v1.16.5-0.20210630124349-1e78734f2cfd

如果还是不行，是否可以提供下最下代码和配置文件；~~

**Comment by feng99** [comment]
> 这个问题我记得是 一个分支问题~ 升级master就好了~
> 
> 你可以在尝试这个分支试试：github.com/gogf/gf v1.16.5-0.20210630124349-1e78734f2cfd
> 
> 如果还是不行，是否可以提供下最下代码和配置文件；~~

-------------------------------------------
go get -u github.com/gogf/gf@v1.16.5-0.20210630124349-1e78734f2cfd
后,运行代码
go: finding module for package go.opentelemetry.io/otel/unit
go: onion-go-cron/app/task/jingcai imports
	onion-go-cron/app/task imports
	github.com/go-redis/redis/v8 imports
	github.com/go-redis/redis/v8/internal imports
	go.opentelemetry.io/otel/metric imports
	go.opentelemetry.io/otel/unit: package provided by go.opentelemetry.io/otel at latest version v0.20.0 but not at required version v1.0.0-RC1

Compilation finished with exit code 1

**Comment by housemecn** [comment]
> > 这个问题我记得是 一个分支问题~ 升级master就好了~
> > 你可以在尝试这个分支试试：github.com/gogf/gf v1.16.5-0.20210630124349-1e78734f2cfd
> > 如果还是不行，是否可以提供下最下代码和配置文件；~~
> 
> go get -u github.com/gogf/gf@v1.16.5-0.20210630124349-1e78734f2cfd
> 后,运行代码
> go: finding module for package go.opentelemetry.io/otel/unit
> go: onion-go-cron/app/task/jingcai imports
> onion-go-cron/app/task imports
> github.com/go-redis/redis/v8 imports
> github.com/go-redis/redis/v8/internal imports
> go.opentelemetry.io/otel/metric imports
> go.opentelemetry.io/otel/unit: package provided by go.opentelemetry.io/otel at latest version v0.20.0 but not at required version v1.0.0-RC1
> 
> Compilation finished with exit code 1

建议你把github.com/go-redis/redis/v8 这个包更新一下，因为这个包引入了otel，后面又移除了，且其中的版本和gf master版本不一致

**Comment by feng99** [comment]
> > > 这个问题我记得是 一个分支问题~ 升级master就好了~
> > > 你可以在尝试这个分支试试：github.com/gogf/gf v1.16.5-0.20210630124349-1e78734f2cfd
> > > 如果还是不行，是否可以提供下最下代码和配置文件；~~
> > 
> > 
> > go get -u github.com/gogf/gf@v1.16.5-0.20210630124349-1e78734f2cfd
> > 后,运行代码
> > go: finding module for package go.opentelemetry.io/otel/unit
> > go: onion-go-cron/app/task/jingcai imports
> > onion-go-cron/app/task imports
> > github.com/go-redis/redis/v8 imports
> > github.com/go-redis/redis/v8/internal imports
> > go.opentelemetry.io/otel/metric imports
> > go.opentelemetry.io/otel/unit: package provided by go.opentelemetry.io/otel at latest version v0.20.0 but not at required version v1.0.0-RC1
> > Compilation finished with exit code 1
> 
> 建议你把github.com/go-redis/redis/v8 这个包更新一下，因为这个包引入了otel，后面又移除了，且其中的版本和gf master版本不一致

---------------------------
我这个项目的go.mod文件里有
gorm.io/driver/mysql v1.1.1
	gorm.io/gorm v1.21.12

和这个有关系吗?
感觉像重复引用导致的

项目里有这个 是历史原因了   额.不能直接删掉

**Comment by housemecn** [comment]
> > > > 这个问题我记得是 一个分支问题~ 升级master就好了~
> > > > 你可以在尝试这个分支试试：github.com/gogf/gf v1.16.5-0.20210630124349-1e78734f2cfd
> > > > 如果还是不行，是否可以提供下最下代码和配置文件；~~
> > > 
> > > 
> > > go get -u github.com/gogf/gf@v1.16.5-0.20210630124349-1e78734f2cfd
> > > 后,运行代码
> > > go: finding module for package go.opentelemetry.io/otel/unit
> > > go: onion-go-cron/app/task/jingcai imports
> > > onion-go-cron/app/task imports
> > > github.com/go-redis/redis/v8 imports
> > > github.com/go-redis/redis/v8/internal imports
> > > go.opentelemetry.io/otel/metric imports
> > > go.opentelemetry.io/otel/unit: package provided by go.opentelemetry.io/otel at latest version v0.20.0 but not at required version v1.0.0-RC1
> > > Compilation finished with exit code 1
> > 
> > 
> > 建议你把github.com/go-redis/redis/v8 这个包更新一下，因为这个包引入了otel，后面又移除了，且其中的版本和gf master版本不一致
> 
> 我这个项目的go.mod文件里有
> gorm.io/driver/mysql v1.1.1
> gorm.io/gorm v1.21.12
> 
> 和这个有关系吗?
> 感觉像重复引用导致的
> 
> 项目里有这个 是历史原因了 额.不能直接删掉
把错误信息发出来吧，不然只能猜测！

**Comment by feng99** [comment]
> > > > > 这个问题我记得是 一个分支问题~ 升级master就好了~
> > > > > 你可以在尝试这个分支试试：github.com/gogf/gf v1.16.5-0.20210630124349-1e78734f2cfd
> > > > > 如果还是不行，是否可以提供下最下代码和配置文件；~~
> > > > 
> > > > 
> > > > go get -u github.com/gogf/gf@v1.16.5-0.20210630124349-1e78734f2cfd
> > > > 后,运行代码
> > > > go: finding module for package go.opentelemetry.io/otel/unit
> > > > go: onion-go-cron/app/task/jingcai imports
> > > > onion-go-cron/app/task imports
> > > > github.com/go-redis/redis/v8 imports
> > > > github.com/go-redis/redis/v8/internal imports
> > > > go.opentelemetry.io/otel/metric imports
> > > > go.opentelemetry.io/otel/unit: package provided by go.opentelemetry.io/otel at latest version v0.20.0 but not at required version v1.0.0-RC1
> > > > Compilation finished with exit code 1
> > > 
> > > 
> > > 建议你把github.com/go-redis/redis/v8 这个包更新一下，因为这个包引入了otel，后面又移除了，且其中的版本和gf master版本不一致
> > 
> > 
> > 我这个项目的go.mod文件里有
> > gorm.io/driver/mysql v1.1.1
> > gorm.io/gorm v1.21.12
> > 和这个有关系吗?
> > 感觉像重复引用导致的
> > 项目里有这个 是历史原因了 额.不能直接删掉
> > 把错误信息发出来吧，不然只能猜测！

-----------------------------------------------------
问题解决了, 我把gorm那部分代码  从main.go 转移到另外一个入口文件了
走俩入口就好了   
谢谢你的回复, 有问题我再提issues

**Comment by gqcn** [comment]
@GuihaiHU 之前可能没合并到`master`分支，你再试试最新的`master`分支呢。新版本的`goframe`使用的是独立`fork`的`mysql`版本 `https://github.com/gogf/mysql` 内部在注册时会有重复判断，我们项目也是用的这个。
