### ISSUE TITLE
panic: empty database configuration for item name '*'

### ISSUE THREAD

**Issue by ysongyang** [gogf/gf#1379]
报错地方做了打印，可以看到有kernel配置的呀。

![image](https://user-images.githubusercontent.com/19664630/130001634-df579b9f-4725-48fb-ae12-75827af5fecc.png)

`E:\GoWorker\go-server\config\config.toml <nil>`
```json
{
        "database": {
                "default": [
                        {
                                "debug": true,
                                "link": "root:123456@tcp(127.0.0.1:3306)/Dev",
                                "type": "mysql"
                        }
                ],
                "kernel": [
                        {
                                "debug": true,
                                "link": "root:123456@tcp(127.0.0.1:3306)/Center",
                                "type": "mysql"
                        }
                ],
                "logger": {
                        "Level": "all",
                        "Path": "/tmp/log/go-server-v2/sql",
                        "Stdout": true
                }
        },
}
```

```
panic: empty database configuration for item name 'kernel'

goroutine 24 [running]:
github.com/gogf/gf/database/gdb.(*Model).getLink(0xc0001ed800, 0x1e80601, 0xc00009e018, 0x7)
        E:/GoWorker/pkg/mod/github.com/gogf/gf@v1.16.1/database/gdb/gdb_model_utility.go:187 +0x269
github.com/gogf/gf/database/gdb.(*Model).Update(0xc0001ed800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        E:/GoWorker/pkg/mod/github.com/gogf/gf@v1.16.1/database/gdb/gdb_model_update.go:87 +0x698
github.com/gogf/gf/database/gdb.(*Model).Update(0xc0001ed800, 0xc0003bdb00, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        E:/GoWorker/pkg/mod/github.com/gogf/gf@v1.16.1/database/gdb/gdb_model_update.go:33 +0x225
go-server-v2/app/model.UpdateTaskDataFromSmS(0xc00009f842, 0x6, 0x1, 0x0, 0xc0005423f0, 0x24, 0xc0001ea4d0, 0x6e, 0x0, 0x0)
        E:/GoWorker/go-server/app/model/sms_template_msg.go:81 +0x7da
go-server-v2/app/service.(*SmSNsqHandler).HandleMessage(0x26214e0, 0xc0001c9500, 0x1a4a060, 0x26214e0)
        E:/GoWorker/go-server/app/service/nsq_consumer.go:129 +0x4c5
github.com/nsqio/go-nsq.(*Consumer).handlerLoop(0xc000126dc0, 0x1e6b480, 0x26214e0)
        E:/GoWorker/pkg/mod/github.com/nsqio/go-nsq@v1.0.8/consumer.go:1113 +0x149
created by github.com/nsqio/go-nsq.(*Consumer).AddConcurrentHandlers
        E:/GoWorker/pkg/mod/github.com/nsqio/go-nsq@v1.0.8/consumer.go:1095 +0x85
exit status 2
```

**Comment by gqcn** [comment]
@ysongyang Can you reproduce this issue using latest version of goframe?
