### ISSUE TITLE
使用uber的goleak检测发现有协程泄漏

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [gogf/gf#1771]
### 1. What version of `Go` and system type/arch are you using?

go version go1.18 linux/amd64

### 2. What version of `GoFrame` are you using?

v2.0.6

### 3. Can this issue be re-produced with the latest release?
yes

### 4. What did you do?

leak_test.go

```golang
package tests

import (
	"go.uber.org/goleak"
	"testing"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
```

logic_test.go

```golang
package tests

import (
	"fmt"
	"github.com/gogf/gf/v2/container/garray"
	"github.com/gogf/gf/v2/os/gtimer"
	"testing"
)

func TestCorrector(t *testing.T) {
	a := garray.New()
	fmt.Println(a)

	b := gtimer.New()
	fmt.Println(b)
}
```

### 5. What did you expect to see?
test passed

### 6. What did you see instead?
```txt
=== RUN   TestCorrector
[]
&{{{0 0} 0 0 0 0} 0xc0000b80d8 0xc0000c0758 0xc0000c0768 {100000000}}
--- PASS: TestCorrector (0.00s)
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 19 in state chan send, with github.com/gogf/gf/v2/util/grand.asyncProducingRandomBufferBytesLoop on top of the stack:
goroutine 19 [chan send]:
github.com/gogf/gf/v2/util/grand.asyncProducingRandomBufferBytesLoop()
	/home/mmc/dev/golang/libs/pkg/mod/github.com/gogf/gf/v2@v2.0.6/util/grand/grand_buffer.go:45 +0xf6
created by github.com/gogf/gf/v2/util/grand.init.0
	/home/mmc/dev/golang/libs/pkg/mod/github.com/gogf/gf/v2@v2.0.6/util/grand/grand_buffer.go:25 +0x2a

 Goroutine 34 in state chan receive, with github.com/gogf/gf/v2/os/gtimer.(*Timer).loop.func1 on top of the stack:
goroutine 34 [chan receive]:
github.com/gogf/gf/v2/os/gtimer.(*Timer).loop.func1()
	/home/mmc/dev/golang/libs/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gtimer/gtimer_timer_loop.go:21 +0xc8
created by github.com/gogf/gf/v2/os/gtimer.(*Timer).loop
	/home/mmc/dev/golang/libs/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gtimer/gtimer_timer_loop.go:13 +0x8f

 Goroutine 23 in state chan receive, with github.com/gogf/gf/v2/os/gtimer.(*Timer).loop.func1 on top of the stack:
goroutine 23 [chan receive]:
github.com/gogf/gf/v2/os/gtimer.(*Timer).loop.func1()
	/home/mmc/dev/golang/libs/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gtimer/gtimer_timer_loop.go:21 +0xc8
created by github.com/gogf/gf/v2/os/gtimer.(*Timer).loop
	/home/mmc/dev/golang/libs/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gtimer/gtimer_timer_loop.go:13 +0x8f
]
```

**Comment by tkzl** [comment]
我也发现了,有60%的几率会在30分钟到40分钟内出现

**Comment by gqcn** [comment]
@ziyouchutuwenwu @tkzl 框架有个别组件会有极少的`goroutine`随着进程/对象启动，随着进程结束自动销毁。根据组件设计和使用场景来讲，是合理。拿你`grand`的`buffer goroutine`来讲，它会异步读取系统随机数据并填充到自身的随机数`buffer channel`中以提高效率。

在分析`goroutine`是否正常关闭时，也应该考虑下场景，不是么？

**Comment by ziyouchutuwenwu** [comment]
抱歉，我只是在跑业务代码的时候，发现哪边不太对，然后看看是不是我的代码有leak, 搜了一圈，看到uber的库，然后做test,我本身没有用到timer组件，用的是gf的并发容器，garray和gmap比较多，test的时候报了这个错误，无法继续做单元，不知道有没有其它的办法能满足我这边的需求，非常感谢

**Comment by gqcn** [comment]
> 抱歉，我只是在跑业务代码的时候，发现哪边不太对，然后看看是不是我的代码有leak, 搜了一圈，看到uber的库，然后做test
> 
> 我本身没有用到timer组件，用的是gf的并发容器，garray和gmap比较多 简化期见，我用garray写的例子，至于timer,是看到有timer的报错，所以在test的时候把timer和garray放了上去
> 
> 从结果上看，放了这个，无法继续做单元，比较影响开发，不知道有没有其它的办法能满足我这边的需求，非常感谢 在找uber的leak库之前，我也希望gf能出一个leak检测的库来检测我的代码问题，但是目前没有找到

`gtimer`是最底层的一个定时器组件，会被定时任务、缓存、日志等组件用到，用于统一出发定时逻辑。你的问题，需要进一步分析`uber leaks`的检测逻辑，按理这种随着进程创建销毁的`goroutine`不应该算`leaks`。
