### ISSUE TITLE
设置多个数据库报错

### ISSUE THREAD

**Issue by tkzl** [gogf/gf#1778]
写了一个数据同步小工具,每次运行时有50%的概率会出现这个报错
```
2022/04/21 14:27:09 sync_goods.go:121: dial tcp 127.0.0.1:3306: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted., SELECT * FROM `a_goods_option` WHERE `goodsid`=200

2022/04/21 14:27:09 sync_goods.go:121: dial tcp 127.0.0.1:3306: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted., SELECT * FROM `a_goods_param` WHERE `goodsid`=200

2022/04/21 14:27:09 sync_goods.go:121: dial tcp 127.0.0.1:3306: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted., SELECT * FROM `a_goods_spec` WHERE `goodsid`=200

2022/04/21 14:27:09 sync_goods.go:121: dial tcp 127.0.0.1:3306: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted., SELECT * FROM `a_goodscode_good` WHERE `goodsid`=200
```
下面是数据库配置
```
# 数据库连接配置
database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  false
    ctxKeys: ["RequestId"]

  default:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "root"
    name: "testa"
    prefix: "a_"
    role: "master"
    debug:  true
    Weight: 1
    MaxIdleConnCount: 5
    MaxOpenConnCount: 20
    MaxConnLifetime: 120
    
  mall:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "root"
    name: "testb"
    prefix: "a_"
    role: "master"
    debug:  true
    Weight: 2
    MaxIdleConnCount: 5
    MaxOpenConnCount: 20
    MaxConnLifetime: 120
    
```
以下是报错代码片段

```
        var AdDb = g.DB("default")
        var MaDb = g.DB("mall")
for{
...
	list_form, err := AdDb.Ctx(ctx).Model(a.getTableName(table_name)).Where(key, id).All()
	list_to, err := MaDb.Ctx(ctx).Model(a.getTableName(table_name)).Where(key, id).All()
...
}
```

**Comment by DGuang21** [comment]
dial tcp 127.0.0.1:3306: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted 说明你本地的服务连接被打满导致的不可用，可尝试使用 `netstat -ano` 查看使用中的端口，并合理设置连接池相关参数，详细可参考 [ORM使用配置](https://goframe.org/pages/viewpage.action?pageId=1114245)

**Comment by tkzl** [comment]
您好，我上次是在公司电脑上出现了那种情况，现在在家里电脑上调试也出现了这种情况，自从换成2.0+经常出现这个，之前1.6+的时候没出现这个，看着像IO等待超时，现在的版本是2.0.6
下面是重编译完成到报错时的完整的报错日志：
Starting: C:\Users\Administrator\go\bin\dlv.exe dap --check-go-version=false --listen=127.0.0.1:50051 from E:\go\products-service
DAP server listening at: 127.0.0.1:50051
Type 'dlv help' for list of commands.
2022-05-06 10:06:14.622 [DEBU] SetServerRoot path: E:\go\products-service\resource\public
2022-05-06 10:06:14.637 [INFO] swagger ui is serving at address: http://127.0.0.1:8166/swagger/
2022-05-06 10:06:14.639 [INFO] openapi specification is serving at address: http://127.0.0.1:8166/api.json
2022-05-06 10:06:14.643 [INFO] pid[22868]: http server started listening on [:8166]
2022-05-06 10:06:18.524 [DEBU] {34f5a71be061ec16363051384417f7cc} [ 16 ms] [default] [rows:8&nbsp; ] SHOW FULL COLUMNS FROM `ps_module`
2022-05-06 10:06:18.548 [DEBU] {34f5a71be061ec16363051384417f7cc} [ 12 ms] [default] [rows:1&nbsp; ] SELECT COUNT(1) FROM `ps_module` WHERE `title` LIKE '%后%'
2022-05-06 10:06:18.550 [DEBU] {34f5a71be061ec16363051384417f7cc} [&nbsp; 1 ms] [default] [rows:1&nbsp; ] SELECT `id`,`title`,`intro`,`create_time`,`update_time`,`delete_time`,`status`,`name` FROM `ps_module` WHERE `title` LIKE '%后%' LIMIT 0,10
2022-05-06 10:06:18.920 {34f5a71be061ec16363051384417f7cc} 200 "GET http 192.168.123.105:8166 /admin/module/lists?keywords=%E5%90%8E&amp;betime= HTTP/1.1" 0.418, 192.168.123.105, "http://192.168.123.105:8166/admin/login/login", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.041 {282c6335e061ec1637305138a0318216} 200 "GET http 192.168.123.105:8166 /static/admin/assets/css/bootstrap.min.css HTTP/1.1" 0.108, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.041 {9ca7cc36e061ec16393051382deaff59} 200 "GET http 192.168.123.105:8166 /static/layer/layer.js HTTP/1.1" 0.083, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.041 {2459d436e061ec163a3051389b18391b} 200 "GET http 192.168.123.105:8166 /static/laydate/laydate.js HTTP/1.1" 0.083, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"&nbsp;
2022-05-06 10:06:19.041 {1ce56a35e061ec1638305138d487dde0} 200 "GET http 192.168.123.105:8166 /static/admin/js/jquery-1.9.1.min.js HTTP/1.1" 0.107, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.063 {1043d03ce061ec163c30513890f75b6a} 200 "GET http 192.168.123.105:8166 /static/laydate/theme/default/laydate.css?v=5.0.9 HTTP/1.1" 0.005, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.063 {d88cc83ce061ec163b30513845a30dba} 200 "GET http 192.168.123.105:8166 /static/layer/theme/default/layer.css?v=3.1.1 HTTP/1.1" 0.006, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.134 [ERRO] {ecf44241e061ec163d3051380d7cbb54} cannot find template file "favicon.ico.html" in following paths:
1. E:\go\products-service\
2. E:\go\products-service\template/
3. E:\go\products-service\resource/template&nbsp;
Stack:
1.&nbsp; github.com/gogf/gf/v2/os/gview.(*View).searchFile
&nbsp; &nbsp; ***@***.***/os/gview/gview_parse.go:451
2.&nbsp; github.com/gogf/gf/v2/os/gview.(*View).ParseOption.func1
&nbsp; &nbsp; ***@***.***/os/gview/gview_parse.go:127
3.&nbsp; github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).doSetWithLockCheck
&nbsp; &nbsp; ***@***.***/container/gmap/gmap_hash_str_any_map.go:215
4.&nbsp; github.com/gogf/gf/v2/container/gmap.(*StrAnyMap).GetOrSetFuncLock
&nbsp; &nbsp; ***@***.***/container/gmap/gmap_hash_str_any_map.go:252
5.&nbsp; github.com/gogf/gf/v2/os/gview.(*View).ParseOption
&nbsp; &nbsp; ***@***.***/os/gview/gview_parse.go:119
6.&nbsp; github.com/gogf/gf/v2/os/gview.(*View).Parse
&nbsp; &nbsp; ***@***.***/os/gview/gview_parse.go:66
7.&nbsp; github.com/gogf/gf/v2/net/ghttp.(*Response).ParseTpl
&nbsp; &nbsp; ***@***.***/net/ghttp/ghttp_response_view.go:66
8.&nbsp; github.com/gogf/gf/v2/net/ghttp.(*Response).WriteTpl
&nbsp; &nbsp; ***@***.***/net/ghttp/ghttp_response_view.go:22
9.&nbsp; products_service/internal/service.(*sView).RenderTpl
&nbsp; &nbsp; E:/go/products-service/internal/service/view.go:72
10. products_service/internal/service.(*sView).Render
&nbsp; &nbsp; E:/go/products-service/internal/service/view.go:82
11. products_service/internal/service.(*sView).Render404
&nbsp; &nbsp; E:/go/products-service/internal/service/view.go:134
12. products_service/internal/cmd.glob..func1.4
&nbsp; &nbsp; E:/go/products-service/internal/cmd/cmd.go:61
13. github.com/gogf/gf/v2/net/ghttp.(*Server).ServeHTTP.func2
&nbsp; &nbsp; ***@***.***/net/ghttp/ghttp_server_handler.go:161
14. github.com/gogf/gf/v2/net/ghttp.niceCallFunc
&nbsp; &nbsp; ***@***.***/net/ghttp/ghttp_func.go:56
15. github.com/gogf/gf/v2/net/ghttp.(*Server).ServeHTTP
&nbsp; &nbsp; ***@***.***/net/ghttp/ghttp_server_handler.go:160
2022-05-06 10:06:19.134 {ecf44241e061ec163d3051380d7cbb54} 404 "GET http 192.168.123.105:8166 /favicon.ico HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.194 [DEBU] {3cdfcd44e061ec163e305138607169c0} [&nbsp; 1 ms] [default] [rows:1&nbsp; ] SELECT COUNT(1) FROM `ps_module` WHERE `title` LIKE '%后%'
2022-05-06 10:06:19.194 [DEBU] {3cdfcd44e061ec163e305138607169c0} [&nbsp; 0 ms] [default] [rows:1&nbsp; ] SELECT `id`,`title`,`intro`,`create_time`,`update_time`,`delete_time`,`status`,`name` FROM `ps_module` WHERE `title` LIKE '%后%' LIMIT 0,10
2022-05-06 10:06:19.218 {3cdfcd44e061ec163e305138607169c0} 200 "GET http 192.168.123.105:8166 /admin/module/lists?keywords=%E5%90%8E&amp;betime= HTTP/1.1" 0.026, 192.168.123.105, "http://192.168.123.105:8166/admin/login/login", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.233 {60a43247e061ec163f3051386971fe5b} 200 "GET http 192.168.123.105:8166 /static/admin/assets/css/bootstrap.min.css HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.234 {d8603a47e061ec164030513887a3625d} 200 "GET http 192.168.123.105:8166 /static/admin/js/jquery-1.9.1.min.js HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"&nbsp;
2022-05-06 10:06:19.234 {d8603a47e061ec1641305138a267b6e2} 200 "GET http 192.168.123.105:8166 /static/layer/layer.js HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"&nbsp;
2022-05-06 10:06:19.234 {74494247e061ec1642305138e169df49} 200 "GET http 192.168.123.105:8166 /static/laydate/laydate.js HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.251 {30cc4848e061ec1643305138c4daf102} 200 "GET http 192.168.123.105:8166 /static/layer/theme/default/layer.css?v=3.1.1 HTTP/1.1" 0.000, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:19.251 {30cc4848e061ec164430513821ec6372} 200 "GET http 192.168.123.105:8166 /static/laydate/theme/default/laydate.css?v=5.0.9 HTTP/1.1" 0.000, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:32.570 [DEBU] {14581162e361ec1645305138ae89b0c3} [&nbsp; 1 ms] [default] [rows:1&nbsp; ] SELECT COUNT(1) FROM `ps_module`
2022-05-06 10:06:32.571 [DEBU] {14581162e361ec1645305138ae89b0c3} [&nbsp; 1 ms] [default] [rows:3&nbsp; ] SELECT `id`,`title`,`intro`,`create_time`,`update_time`,`delete_time`,`status`,`name` FROM `ps_module` LIMIT 0,10
2022-05-06 10:06:32.572 {14581162e361ec1645305138ae89b0c3} 200 "GET http 192.168.123.105:8166 /admin/module/lists?keywords=&amp;betime= HTTP/1.1" 0.004, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=%E5%90%8E&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:32.587 {b48d2663e361ec1646305138ab3bbacf} 200 "GET http 192.168.123.105:8166 /static/admin/assets/css/bootstrap.min.css HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:32.587 {b48d2663e361ec16473051384ae90cb3} 200 "GET http 192.168.123.105:8166 /static/admin/js/jquery-1.9.1.min.js HTTP/1.1" 0.000, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:32.588 {f8412e63e361ec1648305138bc025aea} 200 "GET http 192.168.123.105:8166 /static/layer/layer.js HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:32.588 {c02b3663e361ec1649305138563af149} 200 "GET http 192.168.123.105:8166 /static/laydate/laydate.js HTTP/1.1" 0.000, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:32.624 {546f5c65e361ec164a30513845ab3f5d} 200 "GET http 192.168.123.105:8166 /static/layer/theme/default/layer.css?v=3.1.1 HTTP/1.1" 0.001, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:32.624 {546f5c65e361ec164b3051387fbed28d} 200 "GET http 192.168.123.105:8166 /static/laydate/theme/default/laydate.css?v=5.0.9 HTTP/1.1" 0.000, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:34.504 {680f74d5e361ec164d305138d1441245} 404 "GET http 192.168.123.105:8166 /admin/menu/lists?mid=1 HTTP/1.1" 0.000, 192.168.123.105, "http://192.168.123.105:8166/admin/module/lists?keywords=&amp;betime=", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:34.509 {680f74d5e361ec164c305138a91553eb} 200 "GET http 192.168.123.105:8166 /static/layer/theme/default/loading-1.gif HTTP/1.1" 0.005, 192.168.123.105, "http://192.168.123.105:8166/static/layer/theme/default/layer.css?v=3.1.1", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
2022-05-06 10:06:34.525 {680f74d5e361ec164e3051388d6c004c} 200 "GET http 192.168.123.105:8166 /static/layer/theme/default/icon.png HTTP/1.1" 0.021, 192.168.123.105, "http://192.168.123.105:8166/static/layer/theme/default/layer.css?v=3.1.1", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
Exception 0xc0000008 0x0 0x0 0x7ffb5aca777a
PC=0x7ffb5aca777a
runtime.cgocall(0xe810a0, 0x2186520)
	C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc00052d810 sp=0xc00052d7d8 pc=0xe14aea
syscall.SyscallN(0x7ffb59512c50, {0xc00052d8b8?, 0x3, 0xc000060380?})
	C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x12b fp=0xc00052d898 sp=0xc00052d810 pc=0xe7c14b
syscall.Syscall(0xc00009a6c0?, 0x0?, 0x18b0340?, 0x0?, 0x0?)
	C:/Program Files/Go/src/runtime/syscall_windows.go:476 +0x3b fp=0xc00052d8e0 sp=0xc00052d898 pc=0xe7be3b
syscall.CloseHandle(0x2ac)
	C:/Program Files/Go/src/syscall/zsyscall_windows.go:482 +0x48 fp=0xc00052d950 sp=0xc00052d8e0 pc=0xea1f88
github.com/fsnotify/fsnotify.(*Watcher).startRead(0xc00032b840, 0xc000c5f300)
	***@***.***/windows.go:343 +0x1c7 fp=0xc00052daf8 sp=0xc00052d950 pc=0x1502e67
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00032b840)
	***@***.***/windows.go:512 +0x1073 fp=0xc00052dfc0 sp=0xc00052daf8 pc=0x1504273
github.com/fsnotify/fsnotify.NewWatcher.func1()
	***@***.***/windows.go:47 +0x2b fp=0xc00052dfe0 sp=0xc00052dfc0 pc=0x1500f2b
runtime.goexit()
	C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00052dfe8 sp=0xc00052dfe0 pc=0xe7f7a1
created by github.com/fsnotify/fsnotify.NewWatcher
	***@***.***/windows.go:47 +0x2f3


goroutine 1 [chan receive, 46 minutes]:
github.com/gogf/gf/v2/net/ghttp.(*Server).Run(0xc000518000)
	***@***.***/net/ghttp/ghttp_server.go:423 +0x199
products_service/internal/cmd.glob..func1({0x1a64c98, 0xc00047c2a0}, 0xc00032a880)
	E:/go/products-service/internal/cmd/cmd.go:77 +0x345
github.com/gogf/gf/v2/os/gcmd.(*Command).doRun(0x215b460, {0x1a64c98, 0xc00047c2a0}, 0xc00032a880)
	***@***.***/os/gcmd/gcmd_command_run.go:117 +0x3e5
github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValueError(0x215b460, {0x1a64c98, 0xc00047c210})
	***@***.***/os/gcmd/gcmd_command_run.go:68 +0x15f
github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue(0x215b460, {0x1a64c98, 0xc00047c210})
	***@***.***/os/gcmd/gcmd_command_run.go:32 +0x76
github.com/gogf/gf/v2/os/gcmd.(*Command).Run(0x215b460, {0x1a64c98, 0xc00047c210})
	***@***.***/os/gcmd/gcmd_command_run.go:26 +0x28
main.main()
	E:/go/products-service/main.go:12 +0x35


goroutine 21 [chan send, 46 minutes]:
github.com/gogf/gf/v2/util/grand.asyncProducingRandomBufferBytesLoop()
	***@***.***/util/grand/grand_buffer.go:45 +0x1ff
created by github.com/gogf/gf/v2/util/grand.init.0
	***@***.***/util/grand/grand_buffer.go:25 +0x25


goroutine 3 [chan receive]:
github.com/gogf/gf/v2/os/gtimer.(*Timer).loop.func1()
	***@***.***/os/gtimer/gtimer_timer_loop.go:21 +0xe9
created by github.com/gogf/gf/v2/os/gtimer.(*Timer).loop
	***@***.***/os/gtimer/gtimer_timer_loop.go:13 +0x66


goroutine 11 [chan receive]:
github.com/gogf/gf/v2/container/gqueue.(*Queue).asyncLoopFromListToChannel(0xc0000302a0)
	***@***.***/container/gqueue/gqueue.go:70 +0xe5
created by github.com/gogf/gf/v2/container/gqueue.New
	***@***.***/container/gqueue/gqueue.go:56 +0x2e6


goroutine 13 [select]:
github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).watchLoop.func1()
	***@***.***/os/gfsnotify/gfsnotify_watcher_loop.go:20 +0x127
created by github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).watchLoop
	***@***.***/os/gfsnotify/gfsnotify_watcher_loop.go:18 +0x66


goroutine 14 [chan receive]:
github.com/fsnotify/fsnotify.(*Watcher).Remove(0xc00032b840, {0xc0026ea000, 0x36})
	***@***.***/windows.go:96 +0x1ab
github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).eventLoop.func1()
	***@***.***/os/gfsnotify/gfsnotify_watcher_loop.go:61 +0x109
created by github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).eventLoop
	***@***.***/os/gfsnotify/gfsnotify_watcher_loop.go:54 +0x66


goroutine 16 [IO wait, 46 minutes]:
internal/poll.runtime_pollWait(0xc000ca0b40?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0003741b8, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc000374018, 0xc0005293a8)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).acceptOne(0xc000374000, 0x2f4, {0xc000ca0b40, 0x2, 0x2}, 0xc000374018)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:942 +0xfd
internal/poll.(*FD).Accept(0xc000374000, 0xc0005297d0)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:976 +0x43f
net.(*netFD).accept(0xc000374000)
	C:/Program Files/Go/src/net/fd_windows.go:139 +0xc5
net.(*TCPListener).accept(0xc000494000)
	C:/Program Files/Go/src/net/tcpsock_posix.go:139 +0x55
net.(*TCPListener).Accept(0xc000494000)
	C:/Program Files/Go/src/net/tcpsock.go:288 +0x67
net/http.(*Server).Serve(0xc000396380, {0x1a64560, 0xc000494000})
	C:/Program Files/Go/src/net/http/server.go:3039 +0x4c8
github.com/gogf/gf/v2/net/ghttp.(*gracefulServer).doServe(0xc0000d2f50, {0x1a64c28, 0xc0000ae018})
	***@***.***/net/ghttp/ghttp_server_graceful.go:171 +0x2f6
github.com/gogf/gf/v2/net/ghttp.(*gracefulServer).ListenAndServe(0xc0000d2f50)
	***@***.***/net/ghttp/ghttp_server_graceful.go:78 +0x113
github.com/gogf/gf/v2/net/ghttp.(*Server).startServer.func1(0xc0000d2f50)
	***@***.***/net/ghttp/ghttp_server.go:549 +0x16f
created by github.com/gogf/gf/v2/net/ghttp.(*Server).startServer
	***@***.***/net/ghttp/ghttp_server.go:543 +0x776


goroutine 84 [select, 46 minutes]:
database/sql.(*DB).connectionOpener(0xc00035f1e0, {0x1a64bf0, 0xc000092dc0})
	C:/Program Files/Go/src/database/sql/sql.go:1226 +0xc5
created by database/sql.OpenDB
	C:/Program Files/Go/src/database/sql/sql.go:794 +0x2bd
rax&nbsp; &nbsp; &nbsp;0x15
rbx&nbsp; &nbsp; &nbsp;0x2ac
rcx&nbsp; &nbsp; &nbsp;0x101500028
rdi&nbsp; &nbsp; &nbsp;0x47998ee000
rsi&nbsp; &nbsp; &nbsp;0xc00052d850
rbp&nbsp; &nbsp; &nbsp;0xc00052d800
rsp&nbsp; &nbsp; &nbsp;0x4799bff980
r8&nbsp; &nbsp; &nbsp; 0x4700000070
r9&nbsp; &nbsp; &nbsp; 0xe6664c
r10&nbsp; &nbsp; &nbsp;0x21a19d8cf10
r11&nbsp; &nbsp; &nbsp;0x100
r12&nbsp; &nbsp; &nbsp;0xc00052d7d8
r13&nbsp; &nbsp; &nbsp;0x0
r14&nbsp; &nbsp; &nbsp;0xc000472680
r15&nbsp; &nbsp; &nbsp;0x20
rip&nbsp; &nbsp; &nbsp;0x7ffb5aca777a
rflags&nbsp; 0x200
cs&nbsp; &nbsp; &nbsp; 0x33
fs&nbsp; &nbsp; &nbsp; 0x53
gs&nbsp; &nbsp; &nbsp; 0x2b
Process 22868 has exited with status 2
Detaching
dlv dap (22936) exited with code: 0

**Comment by gqcn** [comment]
初步看了下，不知道什么原因。看起来像是连接池失效了一样，需要调试一下，定时异步打印一下连接池的状态？或者异步观测下数据库的连接状态？
另外需要注意一点，连接池是按照数据库设置的，不同的数据库连接池是独立的。
