### ISSUE TITLE
fsnotify read events panic in windows system

### ISSUE THREAD

**Issue by tkzl** [gogf/gf#1807]
**There is a 60% chance of this happening**

Detaching and terminating target process
dlv dap (18232) exited with code: 0
Starting: C:\Users\Administrator\go\bin\dlv.exe dap --check-go-version=false --listen=127.0.0.1:26150 from E:\go\products-service
DAP server listening at: 127.0.0.1:26150
Type 'dlv help' for list of commands.
```
2022-05-09 16:12:20.617 [DEBU] SetServerRoot path: E:\go\products-service\resource\public
2022-05-09 16:12:20.626 [INFO] swagger ui is serving at address: http://127.0.0.1:8166/swagger/
2022-05-09 16:12:20.626 [INFO] openapi specification is serving at address: http://127.0.0.1:8166/api.json
2022-05-09 16:12:20.630 [INFO] pid[10364]: http server started listening on [:8166]
2022/05/09 16:12:24 &{1 admin  0 admin   map[] 1}
2022-05-09 16:12:24.672 [DEBU] {18711b359861ed1641144d1b2a7aeb5d} [  4 ms] [default] [rows:10 ] SHOW FULL COLUMNS FROM `ps_orst`
2022-05-09 16:12:24.673 [DEBU] {20c05a359861ed1642144d1b1c95a2ef} [  1 ms] [default] [rows:8  ] SELECT * FROM `ps_orst` WHERE (delete_time is null) AND `delete_time` IS NULL

...

2022-05-09 16:13:40.960 [DEBU] {bcef25f6a961ed1658144d1bbd10a03d} [  1 ms] [default] [rows:5  ] SELECT ar.*,oa.auth_rule_id as oa_id FROM `ps_auth_rule` AS ar LEFT JOIN `ps_orst_auth` AS `oa` ON (oa.auth_rule_id=ar.id and oa.orst_id=1) WHERE (`ar`.`group_id`=97) AND `ar`.`delete_time` IS NULL AND `oa`.`delete_time` IS NULL
2022-05-09 16:13:40.962 {bcef25f6a961ed1658144d1bbd10a03d} 200 "POST http 127.0.0.1:8166 /admin/orst/auth_list HTTP/1.1" 0.041, 127.0.0.1, "http://127.0.0.1:8166/admin/orst/auth_list?orst_id=1", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
Exception 0xc0000008 0x0 0x0 0x7ffab044777a
PC=0x7ffab044777a
runtime.cgocall(0xbf10a0, 0xc0006006c0)
	C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc000a77810 sp=0xc000a777d8 pc=0xb84aea
syscall.SyscallN(0x7ffaaf7a2c50, {0xc000a778b8?, 0x3, 0xc0000a4c40?})
	C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x12b fp=0xc000a77898 sp=0xc000a77810 pc=0xbec14b
syscall.Syscall(0xc0000927b0?, 0x0?, 0x164e0c0?, 0x0?, 0x0?)
	C:/Program Files/Go/src/runtime/syscall_windows.go:476 +0x3b fp=0xc000a778e0 sp=0xc000a77898 pc=0xbebe3b
syscall.CloseHandle(0x2c8)
	C:/Program Files/Go/src/syscall/zsyscall_windows.go:482 +0x48 fp=0xc000a77950 sp=0xc000a778e0 pc=0xc67a08
github.com/fsnotify/fsnotify.(*Watcher).startRead(0xc0002fb800, 0xc0003ba000)
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:343 +0x1c7 fp=0xc000a77af8 sp=0xc000a77950 pc=0x1274ac7
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0002fb800)
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:512 +0x1073 fp=0xc000a77fc0 sp=0xc000a77af8 pc=0x1275ed3
github.com/fsnotify/fsnotify.NewWatcher.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:47 +0x2b fp=0xc000a77fe0 sp=0xc000a77fc0 pc=0x1272b8b
runtime.goexit()
	C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000a77fe8 sp=0xc000a77fe0 pc=0xbef7a1
created by github.com/fsnotify/fsnotify.NewWatcher
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:47 +0x2f3

goroutine 1 [chan receive]:
github.com/gogf/gf/v2/net/ghttp.(*Server).Run(0xc00008c300)
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/net/ghttp/ghttp_server.go:423 +0x199
products_service/internal/cmd.glob..func1({0x180d2b8, 0xc00034d560}, 0xc0002fa840)
	E:/go/products-service/internal/cmd/cmd.go:77 +0x345
github.com/gogf/gf/v2/os/gcmd.(*Command).doRun(0x1f108a0, {0x180d2b8, 0xc00034d560}, 0xc0002fa840)
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gcmd/gcmd_command_run.go:117 +0x3e5
github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValueError(0x1f108a0, {0x180d2b8, 0xc00034d4d0})
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gcmd/gcmd_command_run.go:68 +0x15f
github.com/gogf/gf/v2/os/gcmd.(*Command).RunWithValue(0x1f108a0, {0x180d2b8, 0xc00034d4d0})
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gcmd/gcmd_command_run.go:32 +0x76
github.com/gogf/gf/v2/os/gcmd.(*Command).Run(0x1f108a0, {0x180d2b8, 0xc00034d4d0})
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gcmd/gcmd_command_run.go:26 +0x28
main.main()
	E:/go/products-service/main.go:18 +0x51

goroutine 19 [chan send]:
github.com/gogf/gf/v2/util/grand.asyncProducingRandomBufferBytesLoop()
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/util/grand/grand_buffer.go:45 +0x1ff
created by github.com/gogf/gf/v2/util/grand.init.0
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/util/grand/grand_buffer.go:25 +0x25

goroutine 5 [chan receive]:
github.com/gogf/gf/v2/os/gtimer.(*Timer).loop.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gtimer/gtimer_timer_loop.go:21 +0xe9
created by github.com/gogf/gf/v2/os/gtimer.(*Timer).loop
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gtimer/gtimer_timer_loop.go:13 +0x66

goroutine 29 [chan receive]:
github.com/gogf/gf/v2/container/gqueue.(*Queue).asyncLoopFromListToChannel(0xc0000311a0)
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/container/gqueue/gqueue.go:70 +0xe5
created by github.com/gogf/gf/v2/container/gqueue.New
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/container/gqueue/gqueue.go:56 +0x2e6

goroutine 31 [select]:
github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).watchLoop.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gfsnotify/gfsnotify_watcher_loop.go:20 +0x127
created by github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).watchLoop
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gfsnotify/gfsnotify_watcher_loop.go:18 +0x66

goroutine 32 [chan receive]:
github.com/fsnotify/fsnotify.(*Watcher).Remove(0xc0002fb800, {0xc0026ade00, 0x36})
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:96 +0x1ab
github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).eventLoop.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gfsnotify/gfsnotify_watcher_loop.go:61 +0x109
created by github.com/gogf/gf/v2/os/gfsnotify.(*Watcher).eventLoop
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/os/gfsnotify/gfsnotify_watcher_loop.go:54 +0x66

goroutine 107 [select]:
database/sql.(*DB).connectionOpener(0xc00030f860, {0x180d210, 0xc000a0dc80})
	C:/Program Files/Go/src/database/sql/sql.go:1226 +0xc5
created by database/sql.OpenDB
	C:/Program Files/Go/src/database/sql/sql.go:794 +0x2bd

goroutine 50 [IO wait]:
internal/poll.runtime_pollWait(0xc0005abd10?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0003501b8, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc000350018, 0xc0004973a8)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).acceptOne(0xc000350000, 0x16c, {0xc0005abd10, 0x2, 0x2}, 0xc000350018)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:942 +0xfd
internal/poll.(*FD).Accept(0xc000350000, 0xc0004977d0)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:976 +0x43f
net.(*netFD).accept(0xc000350000)
	C:/Program Files/Go/src/net/fd_windows.go:139 +0xc5
net.(*TCPListener).accept(0xc0004a0000)
	C:/Program Files/Go/src/net/tcpsock_posix.go:139 +0x55
net.(*TCPListener).Accept(0xc0004a0000)
	C:/Program Files/Go/src/net/tcpsock.go:288 +0x67
net/http.(*Server).Serve(0xc0004a61c0, {0x180cb40, 0xc0004a0000})
	C:/Program Files/Go/src/net/http/server.go:3039 +0x4c8
github.com/gogf/gf/v2/net/ghttp.(*gracefulServer).doServe(0xc000251260, {0x180d248, 0xc0000aa070})
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/net/ghttp/ghttp_server_graceful.go:171 +0x2f6
github.com/gogf/gf/v2/net/ghttp.(*gracefulServer).ListenAndServe(0xc000251260)
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/net/ghttp/ghttp_server_graceful.go:78 +0x113
github.com/gogf/gf/v2/net/ghttp.(*Server).startServer.func1(0xc000251260)
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/net/ghttp/ghttp_server.go:549 +0x16f
created by github.com/gogf/gf/v2/net/ghttp.(*Server).startServer
	C:/Users/Administrator/go/pkg/mod/github.com/gogf/gf/v2@v2.0.6/net/ghttp/ghttp_server.go:543 +0x776

goroutine 936 [IO wait]:
internal/poll.runtime_pollWait(0xc002386a18?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc002386bb8, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc002386a18, 0x17b1998)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).Read(0xc002386a00, {0xc00097b000, 0x1000, 0x1000})
	C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x47a
net.(*netFD).Read(0xc002386a00, {0xc00097b000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc00063a888, {0xc00097b000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/net.go:183 +0xa9
net/http.(*connReader).Read(0xc001b1e3c0, {0xc00097b000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/http/server.go:780 +0x22c
bufio.(*Reader).fill(0xc000958840)
	C:/Program Files/Go/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc000958840, 0x4)
	C:/Program Files/Go/src/bufio/bufio.go:144 +0x178
net/http.(*conn).serve(0xc002653040, {0x180d210, 0xc001b15240})
	C:/Program Files/Go/src/net/http/server.go:1992 +0x1b16
created by net/http.(*Server).Serve
	C:/Program Files/Go/src/net/http/server.go:3071 +0x9cf

goroutine 878 [IO wait]:
internal/poll.runtime_pollWait(0xc000636018?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0006361b8, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc000636018, 0x17b1998)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).Read(0xc000636000, {0xc000153000, 0x1000, 0x1000})
	C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x47a
net.(*netFD).Read(0xc000636000, {0xc000153000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc00063a000, {0xc000153000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/net.go:183 +0xa9
net/http.(*connReader).Read(0xc000a432f0, {0xc000153000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/http/server.go:780 +0x22c
bufio.(*Reader).fill(0xc000034300)
	C:/Program Files/Go/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc000034300, 0x4)
	C:/Program Files/Go/src/bufio/bufio.go:144 +0x178
net/http.(*conn).serve(0xc0026520a0, {0x180d210, 0xc000a0dfc0})
	C:/Program Files/Go/src/net/http/server.go:1992 +0x1b16
created by net/http.(*Server).Serve
	C:/Program Files/Go/src/net/http/server.go:3071 +0x9cf

goroutine 846 [IO wait]:
internal/poll.runtime_pollWait(0xc0007ad198?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0007ad338, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc0007ad198, 0x17b1998)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).Read(0xc0007ad180, {0xc00082d000, 0x1000, 0x1000})
	C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x47a
net.(*netFD).Read(0xc0007ad180, {0xc00082d000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc000006e70, {0xc00082d000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/net.go:183 +0xa9
net/http.(*connReader).Read(0xc002380990, {0xc00082d000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/http/server.go:780 +0x22c
bufio.(*Reader).fill(0xc002f7fc80)
	C:/Program Files/Go/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc002f7fc80, 0x4)
	C:/Program Files/Go/src/bufio/bufio.go:144 +0x178
net/http.(*conn).serve(0xc002edd040, {0x180d210, 0xc001a453c0})
	C:/Program Files/Go/src/net/http/server.go:1992 +0x1b16
created by net/http.(*Server).Serve
	C:/Program Files/Go/src/net/http/server.go:3071 +0x9cf

goroutine 848 [IO wait]:
internal/poll.runtime_pollWait(0xc0007ad698?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0007ad838, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc0007ad698, 0x17b1998)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).Read(0xc0007ad680, {0xc0023a1000, 0x1000, 0x1000})
	C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x47a
net.(*netFD).Read(0xc0007ad680, {0xc0023a1000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc000006e80, {0xc0023a1000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/net.go:183 +0xa9
net/http.(*connReader).Read(0xc002380ed0, {0xc0023a1000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/http/server.go:780 +0x22c
bufio.(*Reader).fill(0xc001a419e0)
	C:/Program Files/Go/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc001a419e0, 0x4)
	C:/Program Files/Go/src/bufio/bufio.go:144 +0x178
net/http.(*conn).serve(0xc002edd180, {0x180d210, 0xc001a455c0})
	C:/Program Files/Go/src/net/http/server.go:1992 +0x1b16
created by net/http.(*Server).Serve
	C:/Program Files/Go/src/net/http/server.go:3071 +0x9cf

goroutine 847 [IO wait]:
internal/poll.runtime_pollWait(0xc0007ad418?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0007ad5b8, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc0007ad418, 0x17b1998)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).Read(0xc0007ad400, {0xc001a63000, 0x1000, 0x1000})
	C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x47a
net.(*netFD).Read(0xc0007ad400, {0xc001a63000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc000006e78, {0xc001a63000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/net.go:183 +0xa9
net/http.(*connReader).Read(0xc002380e70, {0xc001a63000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/http/server.go:780 +0x22c
bufio.(*Reader).fill(0xc001a41980)
	C:/Program Files/Go/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc001a41980, 0x4)
	C:/Program Files/Go/src/bufio/bufio.go:144 +0x178
net/http.(*conn).serve(0xc002edd0e0, {0x180d210, 0xc001a45500})
	C:/Program Files/Go/src/net/http/server.go:1992 +0x1b16
created by net/http.(*Server).Serve
	C:/Program Files/Go/src/net/http/server.go:3071 +0x9cf

goroutine 933 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/connection.go:614 +0xf8
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	C:/Users/Administrator/go/pkg/mod/github.com/go-sql-driver/mysql@v1.6.0/connection.go:611 +0x13b

goroutine 934 [select]:
database/sql.(*DB).connectionCleaner(0xc00030f860, 0x6fc23ac00)
	C:/Program Files/Go/src/database/sql/sql.go:1069 +0x105
created by database/sql.(*DB).startCleanerLocked
	C:/Program Files/Go/src/database/sql/sql.go:1056 +0x156

goroutine 938 [IO wait]:
internal/poll.runtime_pollWait(0xc002386f18?, 0x72)
	C:/Program Files/Go/src/runtime/netpoll.go:302 +0x45
internal/poll.(*pollDesc).wait(0xc0023870b8, 0x72, 0x0)
	C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:83 +0x88
internal/poll.execIO(0xc002386f18, 0x17b1998)
	C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0x2d0
internal/poll.(*FD).Read(0xc002386f00, {0xc001b22000, 0x1000, 0x1000})
	C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x47a
net.(*netFD).Read(0xc002386f00, {0xc001b22000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/fd_posix.go:55 +0x73
net.(*conn).Read(0xc00063a898, {0xc001b22000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/net.go:183 +0xa9
net/http.(*connReader).Read(0xc001b1e480, {0xc001b22000, 0x1000, 0x1000})
	C:/Program Files/Go/src/net/http/server.go:780 +0x22c
bufio.(*Reader).fill(0xc001b1c780)
	C:/Program Files/Go/src/bufio/bufio.go:106 +0x294
bufio.(*Reader).Peek(0xc001b1c780, 0x4)
	C:/Program Files/Go/src/bufio/bufio.go:144 +0x178
net/http.(*conn).serve(0xc0026530e0, {0x180d210, 0xc001b152c0})
	C:/Program Files/Go/src/net/http/server.go:1992 +0x1b16
created by net/http.(*Server).Serve
	C:/Program Files/Go/src/net/http/server.go:3071 +0x9cf
rax     0xc
rbx     0x2c8
rcx     0x101b4000f
rdi     0x323234d000
rsi     0xc000a77850
rbp     0xc000a77800
rsp     0x3233fff790
r8      0x3200000070
r9      0xbdb275
r10     0x19167dc5e00
r11     0x100
r12     0xc000a777d8
r13     0x0
r14     0xc0006a4680
r15     0x20
rip     0x7ffab044777a
rflags  0x204
cs      0x33
fs      0x53
gs      0x2b
Process 10364 has exited with status 2
Detaching
dlv dap (12184) exited with code: 0
```

**Comment by gqcn** [comment]
@tkzl Your panic information indicates that this panic is caused by syscall from third party `fsnotify`:
```
Exception 0xc0000008 0x0 0x0 0x7ffab044777a
PC=0x7ffab044777a
runtime.cgocall(0xbf10a0, 0xc0006006c0)
	C:/Program Files/Go/src/runtime/cgocall.go:157 +0x4a fp=0xc000a77810 sp=0xc000a777d8 pc=0xb84aea
syscall.SyscallN(0x7ffaaf7a2c50, {0xc000a778b8?, 0x3, 0xc0000a4c40?})
	C:/Program Files/Go/src/runtime/syscall_windows.go:538 +0x12b fp=0xc000a77898 sp=0xc000a77810 pc=0xbec14b
syscall.Syscall(0xc0000927b0?, 0x0?, 0x164e0c0?, 0x0?, 0x0?)
	C:/Program Files/Go/src/runtime/syscall_windows.go:476 +0x3b fp=0xc000a778e0 sp=0xc000a77898 pc=0xbebe3b
syscall.CloseHandle(0x2c8)
	C:/Program Files/Go/src/syscall/zsyscall_windows.go:482 +0x48 fp=0xc000a77950 sp=0xc000a778e0 pc=0xc67a08
github.com/fsnotify/fsnotify.(*Watcher).startRead(0xc0002fb800, 0xc0003ba000)
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:343 +0x1c7 fp=0xc000a77af8 sp=0xc000a77950 pc=0x1274ac7
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0002fb800)
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:512 +0x1073 fp=0xc000a77fc0 sp=0xc000a77af8 pc=0x1275ed3
github.com/fsnotify/fsnotify.NewWatcher.func1()
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:47 +0x2b fp=0xc000a77fe0 sp=0xc000a77fc0 pc=0x1272b8b
runtime.goexit()
	C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000a77fe8 sp=0xc000a77fe0 pc=0xbef7a1
created by github.com/fsnotify/fsnotify.NewWatcher
	C:/Users/Administrator/go/pkg/mod/github.com/fsnotify/fsnotify@v1.5.1/windows.go:47 +0x2f3
```

I'll post this as a issue to fsnotify.
