### ISSUE TITLE
concurrent map writes

### ISSUE THREAD

**Issue by xxxlzj520** [gogf/gf#2545]
goroutine 48835 [running]:
net/textproto.MIMEHeader.Set(...)
        /work_tools/go1.19.7/src/net/textproto/header.go:22
net/http.Header.Set(...)
        /work_tools/go1.19.7/src/net/http/header.go:40
github.com/gogf/gf/v2/net/ghttp.(*Response).WriteJson(0xc0000f4000, {0xfffa40?, 0xc000558160})
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_response_write.go:107 +0xa5
ops-data-back/app/common/apis.Api.WriteJson(...)
        /WorkGo/ops-data-back/app/common/apis/api.go:42
ops-data-back/app/admin/controller.(*rsyncPro).RsyncOss(0xc000010f00, 0xc00038a000)
        /WorkGo/ops-data-back/app/admin/controller/rsynccontroller.go:31 +0x145
github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc.func1()
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_request_middleware.go:131 +0x3f
github.com/gogf/gf/v2/net/ghttp.niceCallFunc(0x0?)
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_func.go:55 +0x3e
github.com/gogf/gf/v2/net/ghttp.(*middleware).callHandlerFunc(0x174f6e6ce3201139?, {0xc00055b6a0, {0x1394238, 0xf4f620}, {0xf4f620, 0xc00055b6a0, 0x13}})
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_request_middleware.go:129 +0x90
github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.4()
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_request_middleware.go:90 +0x66
github.com/gogf/gf/v2/net/ghttp.niceCallFunc(0x10818?)
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_func.go:55 +0x3e
github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1({0x0?, 0x0?})
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_request_middleware.go:89 +0x29c
github.com/gogf/gf/v2/util/gutil.TryCatch({0x13885b8?, 0xc000eda510?}, 0x40d7ff?, {0xc0005e6d70?, 0x203000?, 0x203000?})
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/util/gutil/gutil.go:56 +0x86
github.com/gogf/gf/v2/net/ghttp.(*middleware).Next(0xc000558120)
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_request_middleware.go:49 +0x17a
ops-data-back/app/xrouter.MiddlewareErrorHandler(0xc00038a000)
        /WorkGo/ops-data-back/app/xrouter/router.go:49 +0x29
github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1.5()
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_request_middleware.go:96 +0x2f
github.com/gogf/gf/v2/net/ghttp.niceCallFunc(0x4?)
        /WorkGo/pkg/mod/github.com/gogf/gf/v2@v2.2.6/net/ghttp/ghttp_func.go:55 +0x3e
github.com/gogf/gf/v2/net/ghttp.(*middleware).Next.func1({0x2?, 0x0?})

**Comment by xxxlzj520** [comment]
没有使用map，为什么会报concurrent map writes
