### ISSUE TITLE
gconv.Map OmitEmpty will panic, when nil field has String() method

### ISSUE THREAD

**Issue by shengdoushi** [gogf/gf#3447]
In some generated grpc struct, will panic when gconv.Map. below is the code example:

``` go
package tests

import (
	"fmt"
	"testing"

	"github.com/gogf/gf/v2/util/gconv"
)

type Status int32

func (s Status) String() string {
	return fmt.Sprintf("%d", s)
}

type RoleInfo struct {
	Status *Status `json:"status,omitempty"`
}

func TestOmitEmpty(t *testing.T) {
	data := &RoleInfo{}

	gconv.Map(data, gconv.MapOption{
		OmitEmpty: true,
	})
}

```

panic message:

```
Running tool: /opt/homebrew/bin/go test -timeout 30s -run ^TestOmitEmpty$ user/tests

--- FAIL: TestOmitEmpty (0.00s)
panic: value method user/tests.Status.String called using nil *Status pointer [recovered]
	panic: value method user/tests.Status.String called using nil *Status pointer

goroutine 8 [running]:
testing.tRunner.func1.2({0x1017374a0, 0x140003eabd0})
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1545 +0x1c4
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1548 +0x360
panic({0x1017374a0?, 0x140003eabd0?})
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/panic.go:914 +0x218
user/tests.(*Status).String(0x1400007d9a0?)
	<autogenerated>:1 +0x6c
github.com/gogf/gf/v2/internal/empty.IsEmpty({0x10171a0c0, 0x0?}, {0x0, 0x0, 0x0?})
	/Users/leguan/go/pkg/mod/github.com/gogf/gf/v2@v2.6.4/internal/empty/empty.go:113 +0x9c8
github.com/gogf/gf/v2/util/gconv.doMapConvertForMapOrStructValue({0x1, {0x1016a6860, 0x1400007b838}, {0x1014db5f8, 0x4}, 0x0, {0x0, 0x1, {0x102005c20, 0x5, ...}}, ...})
	/Users/leguan/go/pkg/mod/github.com/gogf/gf/v2@v2.6.4/util/gconv/gconv_map.go:392 +0x710
github.com/gogf/gf/v2/util/gconv.doMapConvert({0x1016a6860, 0x1400007b838}, {0x1014db5f8, 0x4}, 0x0, {0x1400008df38, 0x1, 0x14038dd1d18?})
	/Users/leguan/go/pkg/mod/github.com/gogf/gf/v2@v2.6.4/util/gconv/gconv_map.go:242 +0xb38
github.com/gogf/gf/v2/util/gconv.Map(...)
	/Users/leguan/go/pkg/mod/github.com/gogf/gf/v2@v2.6.4/util/gconv/gconv_map.go:47
user/tests.TestOmitEmpty(0x0?)
	/Users/leguan/projects/leguan/src/user/tests/gf_test.go:23 +0x68
testing.tRunner(0x140003691e0, 0x10189c478)
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 1
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/testing/testing.go:1648 +0x33c
FAIL	user/tests	0.017s
FAIL

```

**Comment by shengdoushi** [comment]
when use protobuf object in orm, will panic :

```go
	_, err := d.Model(ctx).WherePri(id).Data(doData).Update()
```

**Comment by shengdoushi** [comment]
I add a test on goplay:

https://goplay.tools/snippet/OeLo4POKs3R

**Comment by wln32** [comment]
这个问题目前已经在新版本中修复，添加了对nil值的判断，
![2](https://github.com/gogf/gf/assets/49137144/bf9ca9eb-71df-4751-b39d-ca51b6ecb90a)
