### ISSUE TITLE
contrib/drivers/pgsql: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yzy613** [gogf/gf#3746]
### Go version

go version go1.23.0 linux/amd64

### GoFrame version

v2.7.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?

```go
_, err = dao.List.Ctx(ctx).
	Where(dao.List.Columns().ListName, listName).
	Data(g.Map{
		dao.List.Columns().DeletedAt: nil,
		dao.List.Columns().UpdatedAt: gtime.Now(),
	}).
	Unscoped().
	Update()
```

`dao.List.Columns().DeletedAt: nil,`

**Wants**

```sql
UPDATE `list`
SET `deleted_at` = NULL, `updated_at` = NOW()
WHERE `list_name` = ?;
```

### What did you see happen?

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x9debb7]
goroutine 239 [running]:
github.com/gogf/gf/contrib/drivers/pgsql/v2.(*Driver).ConvertValueForField(0xc000192010, {0x1af5358, 0xc00053c2a0}, {0xc00023d4f0, 0xb}, {0>
	github.com/gogf/gf/contrib/drivers/pgsql/v2@v2.7.2/pgsql_convert.go:23 +0x77
github.com/gogf/gf/v2/database/gdb.(*Core).ConvertDataForRecord(0xc000922000, {0x1af5358, 0xc00053c2a0}, {0x16aab00?, 0xc00053c360?}, {0xc0>
	github.com/gogf/gf/v2@v2.7.2/database/gdb/gdb_core_structure.go:66 +0x1b0
github.com/gogf/gf/v2/database/gdb.(*Core).DoUpdate(0xc000922000, {0x1af5358, 0xc00053c2a0}, {0x1af66e0, 0xc0003409a0}, {0xc0005a824a?, 0x9>
	github.com/gogf/gf/v2@v2.7.2/database/gdb/gdb_core.go:600 +0x1d2
github.com/gogf/gf/v2/database/gdb.(*HookUpdateInput).Next(0xc000922090, {0x1af5358, 0xc00053c2a0})
	github.com/gogf/gf/v2@v2.7.2/database/gdb/gdb_model_hook.go:205 +0x323
github.com/gogf/gf/v2/database/gdb.(*Model).Update(0xc000520800, {0x0, 0x0, 0x0})
	github.com/gogf/gf/v2@v2.7.2/database/gdb/gdb_model_update.go:112 +0xb25
```

### What did you expect to see?

No panic

**Comment by yzy613** [comment]
Fixed in #3679
