### ISSUE TITLE
gf/net/gclient/gclient_request.go: panic while post data "@file:"

### ISSUE THREAD

**Issue by FenrirLi** [gogf/gf#3748]
### Go version

go version go1.20 windows/amd64

### GoFrame version

2.2.2

### Can this bug be reproduced with the latest release?

Option Yes

### What did you do?
```go
// post json with json header
c1 := gclient.New()
c1.SetHeader("Content-Type", "application/json")
a1 := map[string]interface{}{
"name": "@file:",
}
r1, _ := cc.Post(ctx, "http://www.google.com", a1)
fmt.Println(r1.Status)

// post string without json header
c2 := gclient.New()
a2 := "@file:"
r2, _ := cc.Post(ctx, "http://www.google.com", a2)
fmt.Println(r2.Status)
```
### What did you see happen?
```
1. exception recovered
   1).  github.com/gogf/gf/v2/net/gclient.(*Client).prepareRequest
        D:/develop/gopath/pkg/mod/github.com/gogf/gf/v2@v2.2.2/net/gclient/gclient_request.go:215
   2).  github.com/gogf/gf/v2/net/gclient.(*Client).DoRequest
        D:/develop/gopath/pkg/mod/github.com/gogf/gf/v2@v2.2.2/net/gclient/gclient_request.go:117
   3).  github.com/gogf/gf/v2/net/gclient.(*Client).Post
        D:/develop/gopath/pkg/mod/github.com/gogf/gf/v2@v2.2.2/net/gclient/gclient_request.go:48
```
### What did you expect to see?

![image](https://github.com/user-attachments/assets/22bf96c6-ddb6-40b1-a3b3-d5e35451d284)
deal this

**Comment by gqcn** [comment]
complete demo codes to reproduce this issue:
```go
package main

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/net/gclient"
)

func main() {
	ctx := context.TODO()
	c1 := gclient.New()
	c1.SetHeader("Content-Type", "application/json")
	a1 := map[string]interface{}{
		"name": "@file:",
	}
	r1, _ := c1.Post(ctx, "http://www.google.com", a1)
	fmt.Println(r1.Status)

	// post string without json header
	c2 := gclient.New()
	a2 := "@file:"
	r2, _ := c2.Post(ctx, "http://www.google.com", a2)
	fmt.Println(r2.Status)
}
```
panic info:
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/gogf/gf/v2/net/gclient.(*Client).prepareRequest(0x140002c60c0, {0x1050e0cd0, 0x1054411c0}, {0x104f6bbfd?, 0x14000031d68?}, {0x104f7691d, 0x15}, {0x14000031ea8, 0x1, 0x1f?})
        /Users/john/Workspace/gogf/gf/net/gclient/gclient_request.go:234 +0x14c8
github.com/gogf/gf/v2/net/gclient.(*Client).DoRequest(0x140002c60c0, {0x1050e0cd0, 0x1054411c0}, {0x104f6bbfd, 0x4}, {0x104f7691d, 0x15}, {0x14000031ea8, 0x1, 0x1})
        /Users/john/Workspace/gogf/gf/net/gclient/gclient_request.go:129 +0xa0
github.com/gogf/gf/v2/net/gclient.(*Client).Post(...)
        /Users/john/Workspace/gogf/gf/net/gclient/gclient_request.go:47
main.main()
        /Users/john/Workspace/gogf/gf/example/.test/main.go:17 +0x398

Process finished with the exit code 2
```
