### ISSUE TITLE
开发环境系统突然奔溃，看不出原因求分析

### ISSUE THREAD

**Issue by tianxia0079** [gogf/gf#694]
部署到线上没有出现过这个问题。

goland开发环境下，次数挺多了。
```
2020-05-29 13:39:25.079 [DEBU] [  2 ms] SELECT * FROM `ai_shop_order` WHERE order_status=0 and channel in ('wx_scan','wx_h5','wx_miniapp')
Exception 0xc0000008 0x0 0x0 0x7ffc2b91feea
PC=0x7ffc2b91feea

syscall.Syscall(0x7ffc2b141e10, 0x1, 0x3b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/runtime/syscall_windows.go:188 +0xbc
syscall.CloseHandle(0x3b0, 0x0, 0x0)
	C:/Go/src/syscall/zsyscall_windows.go:354 +0x71
github.com/fsnotify/fsnotify.(*Watcher).startRead(0xc0001dee80, 0xc000420c00, 0x0, 0x0)
	C:/GOPATH/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/windows.go:342 +0x22e
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc0001dee80)
	C:/GOPATH/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/windows.go:511 +0x25d
created by github.com/fsnotify/fsnotify.NewWatcher
	C:/GOPATH/pkg/mod/github.com/fsnotify/fsnotify@v1.4.7/windows.go:46 +0x312

goroutine 1 [chan receive, 1 minutes]:
github.com/gogf/gf/net/ghttp.(*Server).Run(0xc00043e000)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/net/ghttp/ghttp_server.go:449 +0x180
main.index()
	C:/Users/Administrator/GolandProjects/yunAIYI/main.go:71 +0x279
main.main()
	C:/Users/Administrator/GolandProjects/yunAIYI/main.go:22 +0x18e

goroutine 6 [chan send, 1 minutes]:
github.com/gogf/gf/util/grand.asyncProducingRandomBufferBytesLoop()
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/util/grand/grand_buffer.go:40 +0x333
created by github.com/gogf/gf/util/grand.init.0
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/util/grand/grand_buffer.go:25 +0x3c

goroutine 7 [chan receive]:
github.com/gogf/gf/os/gtimer.(*wheel).start.func1(0xc0000684b0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gtimer/gtimer_loop.go:21 +0x81
created by github.com/gogf/gf/os/gtimer.(*wheel).start
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gtimer/gtimer_loop.go:17 +0x46

goroutine 8 [chan receive]:
github.com/gogf/gf/container/gqueue.(*Queue).asyncLoopFromListToChannel(0xc0001e4060)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/container/gqueue/gqueue.go:72 +0xd0
created by github.com/gogf/gf/container/gqueue.New
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/container/gqueue/gqueue.go:58 +0x2e4

goroutine 10 [select]:
github.com/gogf/gf/os/gfsnotify.(*Watcher).startWatchLoop.func1(0xc0001e40f0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gfsnotify/gfsnotify_watcher_loop.go:18 +0x189
created by github.com/gogf/gf/os/gfsnotify.(*Watcher).startWatchLoop
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gfsnotify/gfsnotify_watcher_loop.go:16 +0x46

goroutine 11 [chan receive]:
github.com/gogf/gf/container/gqueue.(*Queue).Pop(0xc0001e4060, 0x0, 0x0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/container/gqueue/gqueue.go:113 +0x57
github.com/gogf/gf/os/gfsnotify.(*Watcher).startEventLoop.func1(0xc0001e40f0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gfsnotify/gfsnotify_watcher_loop.go:86 +0x5c
created by github.com/gogf/gf/os/gfsnotify.(*Watcher).startEventLoop
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gfsnotify/gfsnotify_watcher_loop.go:84 +0x46

goroutine 34 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1785600)
	C:/GOPATH/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x7a
created by github.com/golang/glog.init.0
	C:/GOPATH/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x22e

goroutine 56 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x288f4f88, 0x72, 0xc0003f02c8)
	C:/Go/src/runtime/netpoll.go:203 +0x65
internal/poll.(*pollDesc).wait(0xc0003f0448, 0x72, 0x168b600, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_poll_runtime.go:87 +0xa2
internal/poll.(*ioSrv).ExecIO(0x1781bb8, 0xc0003f0298, 0xc0004220a0, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:228 +0x2cd
internal/poll.(*FD).acceptOne(0xc0003f0280, 0x340, 0xc00021a000, 0x2, 0x2, 0xc0003f0298, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:896 +0xfa
internal/poll.(*FD).Accept(0xc0003f0280, 0xc000687d10, 0x0, 0x0, 0x0, 0x0, 0xc000000000, 0x0, 0x0, 0x0, ...)
	C:/Go/src/internal/poll/fd_windows.go:930 +0x331
net.(*netFD).accept(0xc0003f0280, 0x0, 0x0, 0x0)
	C:/Go/src/net/fd_windows.go:193 +0xe3
net.(*TCPListener).accept(0xc000422040, 0x0, 0x0, 0x0)
	C:/Go/src/net/tcpsock_posix.go:139 +0x68
net.(*TCPListener).Accept(0xc000422040, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/net/tcpsock.go:261 +0x7f
github.com/gogf/gf/os/gproc.receiveTcpListening()
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gproc/gproc_comm_receive.go:72 +0x3a7
created by github.com/gogf/gf/os/gproc.Receive
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gproc/gproc_comm_receive.go:32 +0x75

goroutine 41 [chan receive, 1 minutes]:
github.com/gogf/gf/container/gqueue.(*Queue).Pop(0xc0001e42d0, 0x0, 0x0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/container/gqueue/gqueue.go:113 +0x57
github.com/gogf/gf/os/gproc.Receive(0xc000429f78, 0x1, 0x1, 0x0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/os/gproc/gproc_comm_receive.go:45 +0x12b
github.com/gogf/gf/net/ghttp.handleProcessMessage()
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/net/ghttp/ghttp_server_admin_process.go:256 +0xa2
created by github.com/gogf/gf/net/ghttp.serverProcessInit
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/net/ghttp/ghttp_server.go:212 +0x21f

goroutine 42 [IO wait]:
internal/poll.runtime_pollWait(0x288f4ea8, 0x72, 0xc00043ea48)
	C:/Go/src/runtime/netpoll.go:203 +0x65
internal/poll.(*pollDesc).wait(0xc00043ebc8, 0x72, 0x168b600, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_poll_runtime.go:87 +0xa2
internal/poll.(*ioSrv).ExecIO(0x1781bb8, 0xc00043ea18, 0xc000095420, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:228 +0x2cd
internal/poll.(*FD).acceptOne(0xc00043ea00, 0x42c, 0xc00025e3c0, 0x2, 0x2, 0xc00043ea18, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:896 +0xfa
internal/poll.(*FD).Accept(0xc00043ea00, 0xc000417860, 0x0, 0x0, 0x0, 0x0, 0xc000000000, 0x0, 0x0, 0x0, ...)
	C:/Go/src/internal/poll/fd_windows.go:930 +0x331
net.(*netFD).accept(0xc00043ea00, 0x0, 0x0, 0x0)
	C:/Go/src/net/fd_windows.go:193 +0xe3
net.(*TCPListener).accept(0xc000512000, 0x0, 0x0, 0x0)
	C:/Go/src/net/tcpsock_posix.go:139 +0x68
net.(*TCPListener).Accept(0xc000512000, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/net/tcpsock.go:261 +0x7f
net/http.(*Server).Serve(0xc0001761c0, 0x112f3e0, 0xc000512000, 0x0, 0x0)
	C:/Go/src/net/http/server.go:2901 +0x432
github.com/gogf/gf/net/ghttp.(*gracefulServer).doServe(0xc0002003c0, 0x0, 0x0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/net/ghttp/ghttp_server_graceful.go:148 +0x333
github.com/gogf/gf/net/ghttp.(*gracefulServer).ListenAndServe(0xc0002003c0, 0x0, 0x0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/net/ghttp/ghttp_server_graceful.go:75 +0x131
github.com/gogf/gf/net/ghttp.(*Server).startServer.func1(0xc00043e000, 0xc0002003c0)
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/net/ghttp/ghttp_server.go:561 +0x467
created by github.com/gogf/gf/net/ghttp.(*Server).startServer
	C:/GOPATH/pkg/mod/github.com/gogf/gf@v1.13.0/net/ghttp/ghttp_server.go:555 +0x688

goroutine 43 [IO wait]:
internal/poll.runtime_pollWait(0x288f4dc8, 0x72, 0xc0002cca18)
	C:/Go/src/runtime/netpoll.go:203 +0x65
internal/poll.(*pollDesc).wait(0xc0002ccbc8, 0x72, 0x168b600, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_poll_runtime.go:87 +0xa2
internal/poll.(*ioSrv).ExecIO(0x1781bb8, 0xc0002cca18, 0x103b5c8, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:228 +0x2cd
internal/poll.(*FD).Read(0xc0002cca00, 0xc0001d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:527 +0x53b
net.(*netFD).Read(0xc0002cca00, 0xc0001d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/net/fd_windows.go:152 +0x94
net.(*conn).Read(0xc0002c04d8, 0xc0001d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/net/net.go:184 +0xbc
net/http.(*connReader).Read(0xc00047e150, 0xc0001d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/net/http/server.go:786 +0x2c9
bufio.(*Reader).fill(0xc000066060)
	C:/Go/src/bufio/bufio.go:100 +0x2d0
bufio.(*Reader).Peek(0xc000066060, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/bufio/bufio.go:138 +0x148
net/http.(*conn).serve(0xc000105720, 0x1130ee0, 0xc0001ded80)
	C:/Go/src/net/http/server.go:1920 +0x196f
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2933 +0x938

goroutine 47 [select, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc0000b5500, 0x1130ee0, 0xc000470440)
	C:/Go/src/database/sql/sql.go:1052 +0xf8
created by database/sql.OpenDB
	C:/Go/src/database/sql/sql.go:722 +0x2a3

goroutine 48 [select]:
database/sql.(*DB).connectionResetter(0xc0000b5500, 0x1130ee0, 0xc000470440)
	C:/Go/src/database/sql/sql.go:1065 +0x126
created by database/sql.OpenDB
	C:/Go/src/database/sql/sql.go:723 +0x2d9

goroutine 67 [select]:
database/sql.(*DB).connectionCleaner(0xc0000b5500, 0x6fc23ac00)
	C:/Go/src/database/sql/sql.go:950 +0x14d
created by database/sql.(*DB).startCleanerLocked
	C:/Go/src/database/sql/sql.go:937 +0x10b

goroutine 2034 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc000300840, 0xc0008db7a0, 0xc00006aa20)
	C:/GOPATH/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0x113
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	C:/GOPATH/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xeb

goroutine 2121 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc0000a10e0, 0xc0007da000, 0xc0000d8d20)
	C:/GOPATH/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0x113
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
	C:/GOPATH/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xeb

goroutine 1687 [IO wait]:
internal/poll.runtime_pollWait(0x288f4ce8, 0x72, 0xc00088e518)
	C:/Go/src/runtime/netpoll.go:203 +0x65
internal/poll.(*pollDesc).wait(0xc00088e6c8, 0x72, 0x168b600, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_poll_runtime.go:87 +0xa2
internal/poll.(*ioSrv).ExecIO(0x1781bb8, 0xc00088e518, 0x103b5c8, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:228 +0x2cd
internal/poll.(*FD).Read(0xc00088e500, 0xc00080e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/internal/poll/fd_windows.go:527 +0x53b
net.(*netFD).Read(0xc00088e500, 0xc00080e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/net/fd_windows.go:152 +0x94
net.(*conn).Read(0xc0003081f0, 0xc00080e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/net/net.go:184 +0xbc
net/http.(*connReader).Read(0xc000f05d40, 0xc00080e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	C:/Go/src/net/http/server.go:786 +0x2c9
bufio.(*Reader).fill(0xc000201620)
	C:/Go/src/bufio/bufio.go:100 +0x2d0
bufio.(*Reader).ReadSlice(0xc000201620, 0x2af6ff0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/bufio/bufio.go:359 +0x3a0
bufio.(*Reader).ReadLine(0xc000201620, 0x0, 0x0, 0x0, 0x2b598200, 0x0, 0x0)
	C:/Go/src/bufio/bufio.go:388 +0x8f
net/textproto.(*Reader).readLineSlice(0xc000f05d70, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/net/textproto/reader.go:58 +0xbe
net/textproto.(*Reader).ReadLine(0xc000f05d70, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/net/textproto/reader.go:39 +0x76
net/http.readRequest(0xc000201620, 0x1400, 0xc0008c5900, 0x0, 0x0)
	C:/Go/src/net/http/request.go:1015 +0xbd
net/http.(*conn).readRequest(0xc0002c83c0, 0x1130ee0, 0xc000471a00, 0x0, 0x0, 0x0)
	C:/Go/src/net/http/server.go:966 +0x50e
net/http.(*conn).serve(0xc0002c83c0, 0x1130ee0, 0xc000471a00)
	C:/Go/src/net/http/server.go:1822 +0xd11
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2933 +0x938
rax     0x1f20000
rbx     0x3b0
rcx     0x1f6b500
rdi     0x23a000
rsi     0xc0003d3880
rbp     0xc0003d3820
rsp     0x27bafd20
r8      0x0
r9      0xd
r10     0x1210470
r11     0x1027baf898
r12     0x2030000
r13     0x0
r14     0x20
r15     0x8
rip     0x7ffc2b91feea
rflags  0x200
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by gqcn** [comment]
@tianxia0079 这个问题像是底层系统`API`报上来的，猜测和`inotify`有关系，你看看你的IDE的工程目录是不是文件太多了。
