### ISSUE TITLE
association problem

### ISSUE THREAD

**Issue by SliverHorn** [gogf/gf#920]
### 1. What version of `Go` and system type/arch are you using?

go version `go1.14.4 darwin/amd64`

### 2. What version of `GoFrame` are you using?

```go
github.com/gogf/gf v1.13.7
```

### 3. Can this issue be reproduced with the latest release?

of course

### 4. What did you do?

- Code
```go
func TestGetCustomersList(t *testing.T) {
	var err error
	var total int
	datalist := ([]*customers.CustomerHasOneAdmin)(nil)
	db := g.DB("default").Table("customers").Safe()
	adminDb := g.DB("default").Table("admins").Safe()
	total, err = db.Count()
	err = db.Limit(10).Offset(0).Structs(&datalist)
	err = adminDb.Where("id", gdb.ListItemValues(datalist, "Customers", "SysUserId")).ScanList(&datalist, "Admin", "Customers", "id:Id")
	if err != nil {
		panic(err)
	}
	fmt.Println(total)
	fmt.Println(datalist)
}
```

- Model
```go
// Admin Model
type Admin struct {
	Id          uint        `orm:"id,primary"   json:"ID"`          // 自增ID
	CreateAt    *gtime.Time `orm:"create_at"    json:"CreatedAt"`   // 创建时间
	UpdateAt    *gtime.Time `orm:"update_at"    json:"UpdatedAt"`   // 更新时间
	DeleteAt    *gtime.Time `orm:"delete_at"    json:"DeletedAt"`   // 删除时间
	Uuid        string      `orm:"uuid"         json:"uuid"`        // 用户唯一标识UUID
	Nickname    string      `orm:"nickname"     json:"nickName"`    // 用户昵称
	HeaderImg   string      `orm:"header_img"   json:"headerImg"`   // 用户头像
	AuthorityId string      `orm:"authority_id" json:"authorityId"` // 用户角色ID
	Username    string      `orm:"username"     json:"userName"`    // 用户名
	Password    string      `orm:"password"     json:"-"`           // 用户登录密码
}

// Custom Model
type Customers struct {
	Id                 uint        `orm:"id,primary" json:"ID"`                            // 自增ID
	CreateAt           *gtime.Time `orm:"create_at" json:"CreatedAt"`                      // 创建时间
	UpdateAt           *gtime.Time `orm:"update_at" json:"UpdatedAt"`                      // 更新时间
	DeleteAt           *gtime.Time `orm:"delete_at" json:"DeletedAt"`                      // 删除时间
	CustomerName       string      `orm:"customer_name" json:"customerName"`               // 客户名
	CustomerPhoneData  string      `orm:"customer_phone_data" json:"customerPhoneData"`    // 客户电话
	SysUserId          int         `orm:"sys_user_id" json:"sysUserId"`                    // 负责员工id
	SysUserAuthorityId string      `orm:"sys_user_authority_id" json:"sysUserAuthorityID"` // 负责员工角色
}

type CustomerHasOneAdmin struct {
	*Customers
	Admin *admins.Admin `json:"sysUser"`
}
```

### 5. What did you expect to see?

The Admin of the two data in the `dataList` has data，The first Admin can successfully get information, but the second one cannot get information

### 6. What did you see instead?

- Data obtained by debug
![image](https://user-images.githubusercontent.com/45428434/94335906-7312fb80-0011-11eb-9d18-6c96a657244d.png)

- Database data from operations table
![image](https://user-images.githubusercontent.com/45428434/94335931-a190d680-0011-11eb-9d20-c918c5820962.png)

- Database data from admins table
![image](https://user-images.githubusercontent.com/45428434/94335968-f7fe1500-0011-11eb-9050-f14c44915bab.png)

### 7. Error stack and sql printing

```
/usr/local/go/bin/go tool test2json -t /Applications/GoLand.app/Contents/plugins/go/lib/dlv/mac/dlv --listen=0.0.0.0:50826 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec /private/var/folders/tx/sx5nzk7d1n5444hfrpj41x180000gn/T/___server_app_service__TestGetCustomersList -- -test.v -test.run ^\QTestGetCustomersList\E$
API server listening at: [::]:50826
=== RUN   TestGetCustomersList
2020-09-26 15:57:55.590 [DEBU] [  2 ms] [default] SHOW FULL COLUMNS FROM `customers`
2020-09-26 15:57:55.591 [DEBU] [  0 ms] [default] SELECT COUNT(1) FROM `customers` WHERE `delete_at` IS NULL
2020-09-26 15:57:55.591 [DEBU] [  0 ms] [default] SELECT * FROM `customers` WHERE `delete_at` IS NULL LIMIT 10 OFFSET 0
2020-09-26 15:57:55.593 [DEBU] [  1 ms] [default] SHOW FULL COLUMNS FROM `admins`
2020-09-26 15:57:55.593 [DEBU] [  0 ms] [default] SELECT * FROM `admins` WHERE `id` IN (1,1) AND `delete_at` IS NULL
--- FAIL: TestGetCustomersList (0.01s)
panic: invalid params:  [recovered]
	panic: invalid params: 

goroutine 20 [running]:
testing.tRunner.func1.1(0x1a9ab00, 0xc0002caec0)
	/usr/local/go/src/testing/testing.go:940 +0x4dc
testing.tRunner.func1(0xc00015e000)
	/usr/local/go/src/testing/testing.go:943 +0x317
panic(0x1a9ab00, 0xc0002caec0)
	/usr/local/go/src/runtime/panic.go:975 +0x41b
server/app/service.TestGetCustomersList(0xc00015e000)
	/Users/sliverhorn/Go/src/github.com/flipped-aurora/gf-vue-admin/server/app/service/customers_test.go:37 +0xa4c
testing.tRunner(0xc00015e000, 0x1b7d158)
	/usr/local/go/src/testing/testing.go:991 +0x18a
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x660

调试器完成，并显示退出代码 0
```

**Comment by SliverHorn** [comment]
> 二次修改代码
- Code
```go
func TestGetCustomersList(t *testing.T) {
	var err error
	datalist := ([]*customers.CustomerHasOneAdmin)(nil)
	db := g.DB("default").Table("customers").Safe()
	adminDb := g.DB("default").Table("admins").Safe()
	err = db.ScanList(&datalist, "Customer")
	err = adminDb.
		Where("id", gdb.ListItemValues(datalist, "Customer", "SysUserId")).
		ScanList(&datalist, "Admin", "Customer", "id:Id")
	if err != nil {
		panic(err)
	}
	fmt.Println(datalist)
}
```
- Model
```go
// Admin Model
type Admin struct {
	Id          uint        `orm:"id,primary"   json:"ID"`          // 自增ID
	CreateAt    *gtime.Time `orm:"create_at"    json:"CreatedAt"`   // 创建时间
	UpdateAt    *gtime.Time `orm:"update_at"    json:"UpdatedAt"`   // 更新时间
	DeleteAt    *gtime.Time `orm:"delete_at"    json:"DeletedAt"`   // 删除时间
	Uuid        string      `orm:"uuid"         json:"uuid"`        // 用户唯一标识UUID
	Nickname    string      `orm:"nickname"     json:"nickName"`    // 用户昵称
	HeaderImg   string      `orm:"header_img"   json:"headerImg"`   // 用户头像
	AuthorityId string      `orm:"authority_id" json:"authorityId"` // 用户角色ID
	Username    string      `orm:"username"     json:"userName"`    // 用户名
	Password    string      `orm:"password"     json:"-"`           // 用户登录密码
}

// Custom Model
type Customers struct {
	Id                 uint        `orm:"id,primary" json:"ID"`                            // 自增ID
	CreateAt           *gtime.Time `orm:"create_at" json:"CreatedAt"`                      // 创建时间
	UpdateAt           *gtime.Time `orm:"update_at" json:"UpdatedAt"`                      // 更新时间
	DeleteAt           *gtime.Time `orm:"delete_at" json:"DeletedAt"`                      // 删除时间
	CustomerName       string      `orm:"customer_name" json:"customerName"`               // 客户名
	CustomerPhoneData  string      `orm:"customer_phone_data" json:"customerPhoneData"`    // 客户电话
	SysUserId          int         `orm:"sys_user_id" json:"sysUserId"`                    // 负责员工id
	SysUserAuthorityId string      `orm:"sys_user_authority_id" json:"sysUserAuthorityID"` // 负责员工角色
}


type CustomerHasOneAdmin struct {
	Customer *Customers
	Admin    *admins.Admin `json:"sysUser"`
}
```
- Data obtained by debug
![image](https://user-images.githubusercontent.com/45428434/94339574-71efc780-002d-11eb-828b-7fc582b34805.png)
- Error stack and sql printing
```
API server listening at: [::]:55978
=== RUN   TestGetCustomersList
2020-09-26 19:20:57.949 [DEBU] [  2 ms] [default] SHOW FULL COLUMNS FROM `customers`
2020-09-26 19:20:57.950 [DEBU] [  0 ms] [default] SELECT * FROM `customers` WHERE `delete_at` IS NULL
2020-09-26 19:20:57.951 [DEBU] [  1 ms] [default] SHOW FULL COLUMNS FROM `admins`
2020-09-26 19:20:57.952 [DEBU] [  0 ms] [default] SELECT * FROM `admins` WHERE `id` IN (1,1) AND `delete_at` IS NULL
--- FAIL: TestGetCustomersList (0.01s)
panic: invalid params:  [recovered]
	panic: invalid params: 

goroutine 15 [running]:
testing.tRunner.func1.1(0x1ab26e0, 0xc0001e04c0)
	/usr/local/go/src/testing/testing.go:940 +0x4dc
testing.tRunner.func1(0xc0002ac900)
	/usr/local/go/src/testing/testing.go:943 +0x317
panic(0x1ab26e0, 0xc0001e04c0)
	/usr/local/go/src/runtime/panic.go:975 +0x41b
server/app/service.TestGetCustomersList(0xc0002ac900)
	/Users/sliverhorn/Go/src/github.com/flipped-aurora/gf-vue-admin/server/app/service/customers_test.go:37 +0x8a3
testing.tRunner(0xc0002ac900, 0x1b97ac8)
	/usr/local/go/src/testing/testing.go:991 +0x18a
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x660

调试器完成，并显示退出代码 0
```


```

**Comment by gqcn** [comment]
@SliverHorn 麻烦给下可复现该问题的包含结构和数据的SQL，以便我本地复现一下。

**Comment by SliverHorn** [comment]
> @SliverHorn 麻烦给下可复现该问题的包含结构和数据的SQL，以便我本地复现一下。

- SQL
```sql
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for admins
-- ----------------------------
DROP TABLE IF EXISTS `admins`;
CREATE TABLE `admins` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `create_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `delete_at` timestamp NULL DEFAULT NULL COMMENT '删除时间',
  `uuid` varchar(255) DEFAULT NULL COMMENT '用户唯一标识UUID',
  `nickname` varchar(255) DEFAULT 'QMPlusUser' COMMENT '用户昵称',
  `header_img` varchar(255) DEFAULT 'http://www.henrongyi.top/avatar/lufu.jpg' COMMENT '用户头像',
  `authority_id` varchar(255) DEFAULT '888' COMMENT '用户角色ID',
  `username` varchar(255) DEFAULT NULL COMMENT '用户名',
  `password` varchar(255) DEFAULT NULL COMMENT '用户登录密码',
  PRIMARY KEY (`id`),
  KEY `idx_admins_deleted_at` (`delete_at`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of admins
-- ----------------------------
BEGIN;
INSERT INTO `admins` VALUES (1, '2020-09-26 13:28:00', '2020-09-26 13:29:16', NULL, 'b4c54e5a-d015-4f8c-9f01-624c527a63ae', '超级管理员', 'http://qmplusimg.henrongyi.top/gvalogo.png', '888', 'admin', '$2a$10$zF5PNCWobve/0RBk.3k03eAGwyvDevFBFd3AZUwETjMhYpZwNooba');
INSERT INTO `admins` VALUES (2, '2020-09-26 13:28:00', '2020-09-26 13:28:00', NULL, 'fd6ef79b-944c-4888-8377-abe2d2608858', 'QMPlusUser', 'http://qmplusimg.henrongyi.top/1572075907logo.png', '9528', 'a303176530', '$2a$10$zF5PNCWobve/0RBk.3k03eAGwyvDevFBFd3AZUwETjMhYpZwNooba');
COMMIT;

-- ----------------------------
-- Table structure for customers
-- ----------------------------
DROP TABLE IF EXISTS `customers`;
CREATE TABLE `customers` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `create_at` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `update_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
  `delete_at` timestamp NULL DEFAULT NULL COMMENT '删除时间',
  `customer_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '客户名',
  `customer_phone_data` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '客户电话',
  `sys_user_id` int unsigned DEFAULT NULL COMMENT '负责员工id',
  `sys_user_authority_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT '负责员工角色',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_exa_customers_deleted_at` (`delete_at`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPACT;

-- ----------------------------
-- Records of customers
-- ----------------------------
BEGIN;
INSERT INTO `customers` VALUES (1, '2020-09-26 14:10:55', '2020-09-26 14:10:57', NULL, '1', '1111111', 1, '888');
INSERT INTO `customers` VALUES (3, '2020-09-26 15:57:27', '2020-09-26 15:57:29', NULL, '1', '1111111', 1, '888');
COMMIT;
```
- Model
```go
// Admin Model
type Admin struct {
	Id          uint        `orm:"id,primary"   json:"ID"`          // 自增ID
	CreateAt    *gtime.Time `orm:"create_at"    json:"CreatedAt"`   // 创建时间
	UpdateAt    *gtime.Time `orm:"update_at"    json:"UpdatedAt"`   // 更新时间
	DeleteAt    *gtime.Time `orm:"delete_at"    json:"DeletedAt"`   // 删除时间
	Uuid        string      `orm:"uuid"         json:"uuid"`        // 用户唯一标识UUID
	Nickname    string      `orm:"nickname"     json:"nickName"`    // 用户昵称
	HeaderImg   string      `orm:"header_img"   json:"headerImg"`   // 用户头像
	AuthorityId string      `orm:"authority_id" json:"authorityId"` // 用户角色ID
	Username    string      `orm:"username"     json:"userName"`    // 用户名
	Password    string      `orm:"password"     json:"-"`           // 用户登录密码
}

// Custom Model
type Customers struct {
	Id                 uint        `orm:"id,primary" json:"ID"`                            // 自增ID
	CreateAt           *gtime.Time `orm:"create_at" json:"CreatedAt"`                      // 创建时间
	UpdateAt           *gtime.Time `orm:"update_at" json:"UpdatedAt"`                      // 更新时间
	DeleteAt           *gtime.Time `orm:"delete_at" json:"DeletedAt"`                      // 删除时间
	CustomerName       string      `orm:"customer_name" json:"customerName"`               // 客户名
	CustomerPhoneData  string      `orm:"customer_phone_data" json:"customerPhoneData"`    // 客户电话
	SysUserId          int         `orm:"sys_user_id" json:"sysUserId"`                    // 负责员工id
	SysUserAuthorityId string      `orm:"sys_user_authority_id" json:"sysUserAuthorityID"` // 负责员工角色
}


type CustomerHasOneAdmin struct {
        *Customers
	Admin    *admins.Admin `json:"sysUser"`
}
```
- service
```go
func TestGetCustomersList(t *testing.T) {
	var err error
	var total int
	datalist := ([]*customers.CustomerHasOneAdmin)(nil)
	db := g.DB("default").Table("customers").Safe()
	adminDb := g.DB("default").Table("admins").Safe()
	total, err = db.Count()
	err = db.Limit(10).Offset(0).Structs(&datalist)
	err = adminDb.Where("id", gdb.ListItemValues(datalist, "Customers", "SysUserId")).ScanList(&datalist, "Admin", "Customers", "id:Id")
	if err != nil {
		panic(err)
	}
	fmt.Println(total)
	fmt.Println(datalist)
}
```

**Comment by gqcn** [comment]
@SliverHorn Please update your `gf` to master branch and try again.

**Comment by SliverHorn** [comment]
> @SliverHorn Please update your `gf` to master branch and try again.

@gqcn Still failed to retrieve data in the master branch
- When querying multiple data, the first data is successful, as long as the associated field values ​​are the same, it cannot be associated
- go.mod
![image](https://user-images.githubusercontent.com/45428434/94509181-41cf4100-0246-11eb-941c-e6276010d116.png)

**Comment by gqcn** [comment]
@SliverHorn BTW, the git push of last night is failed, maybe this is the reason you still failing. Use the latest master brach codes and try again.
